### ISSUE TITLE
Somes issues and how to enable cuda support

### ISSUE THREAD

**Issue by dignome** [justinjohn0306/MaskGCT-Windows#2]
When you first run "python app.py" it complains there is no spaces module installed.  Once you fix that it informs you the Cuda provider is not being used.

I added onnxruntime-gpu and spaces to the requirements.txt.

Then installed Nvidia computing toolkit 12.6 and the cudnn 9.5 Installer (win10) on my Windows 11 machine.  For cudnn go to 

C:\Program Files\NVIDIA\CUDNN\v9.5 and copy the files in bin, include, and lib into the similar locations in:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6

You won't get the Cuda exeuction provider warning any more but the program will still use the cpu - to fix it do the next step.

Finally go to https://pytorch.org/get-started/locally/ - select the appropriate options - I used cuda 12.4 install command within the conda environment.

**Comment by justinjohn0306** [comment]
> When you first run "python app.py" it complains there is no spaces module installed. Once you fix that it informs you the Cuda provider is not being used.
> 
> I added onnxruntime-gpu and spaces to the requirements.txt.
> 
> Then installed Nvidia computing toolkit 12.6 and the cudnn 9.5 Installer (win10) on my Windows 11 machine. For cudnn go to
> 
> C:\Program Files\NVIDIA\CUDNN\v9.5 and copy the files in bin, include, and lib into the similar locations in: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6
> 
> You won't get the Cuda exeuction provider warning any more but the program will still use the cpu - to fix it do the next step.
> 
> Finally go to https://pytorch.org/get-started/locally/ - select the appropriate options - I used cuda 12.4 install command within the conda environment.

Thanks, I forgot to update these instructions :)
