### ISSUE TITLE
RuntimeError: failed to load voice "ja"

### ISSUE THREAD

**Issue by zachysaur** [justinjohn0306/MaskGCT-Windows#3]
(venv) F:\maskgct\maskgct>python app.py
./models/tts/maskgct/g2p\sources\g2p_chinese_model\poly_bert_model.onnx
Error: Could not load the specified mbrola voice file.
Error: Could not load the specified mbrola voice file.
Traceback (most recent call last):
  File "F:\maskgct\maskgct\app.py", line 18, in <module>
    from models.tts.maskgct.g2p.g2p_generation import g2p, chn_eng_g2p
  File "F:\maskgct\maskgct\models\tts\maskgct\g2p\g2p_generation.py", line 10, in <module>
    from models.tts.maskgct.g2p.utils.g2p import phonemizer_g2p
  File "F:\maskgct\maskgct\models\tts\maskgct\g2p\utils\g2p.py", line 30, in <module>
    phonemizer_ja = EspeakBackend(
  File "F:\maskgct\maskgct\venv\lib\site-packages\phonemizer\backend\espeak\espeak.py", line 49, in __init__
    self._espeak.set_voice(language)
  File "F:\maskgct\maskgct\venv\lib\site-packages\phonemizer\backend\espeak\wrapper.py", line 249, in set_voice
    raise RuntimeError(  # pragma: nocover
RuntimeError: failed to load voice "ja"

(venv) F:\maskgct\maskgct>

**Comment by justinjohn0306** [comment]
> (venv) F:\maskgct\maskgct>python app.py ./models/tts/maskgct/g2p\sources\g2p_chinese_model\poly_bert_model.onnx Error: Could not load the specified mbrola voice file. Error: Could not load the specified mbrola voice file. Traceback (most recent call last): File "F:\maskgct\maskgct\app.py", line 18, in from models.tts.maskgct.g2p.g2p_generation import g2p, chn_eng_g2p File "F:\maskgct\maskgct\models\tts\maskgct\g2p\g2p_generation.py", line 10, in from models.tts.maskgct.g2p.utils.g2p import phonemizer_g2p File "F:\maskgct\maskgct\models\tts\maskgct\g2p\utils\g2p.py", line 30, in phonemizer_ja = EspeakBackend( File "F:\maskgct\maskgct\venv\lib\site-packages\phonemizer\backend\espeak\espeak.py", line 49, in **init** self._espeak.set_voice(language) File "F:\maskgct\maskgct\venv\lib\site-packages\phonemizer\backend\espeak\wrapper.py", line 249, in set_voice raise RuntimeError( # pragma: nocover RuntimeError: failed to load voice "ja"
> 
> (venv) F:\maskgct\maskgct>

fixed~ try running ``pip install -r requirements.txt`` again

**Comment by jasoncow007** [comment]
> > (venv) F:\maskgct\maskgct>python app.py ./models/tts/maskgct/g2p\sources\g2p_chinese_model\poly_bert_model.onnx Error: Could not load the specified mbrola voice file. Error: Could not load the specified mbrola voice file. Traceback (most recent call last): File "F:\maskgct\maskgct\app.py", line 18, in from models.tts.maskgct.g2p.g2p_generation import g2p, chn_eng_g2p File "F:\maskgct\maskgct\models\tts\maskgct\g2p\g2p_generation.py", line 10, in from models.tts.maskgct.g2p.utils.g2p import phonemizer_g2p File "F:\maskgct\maskgct\models\tts\maskgct\g2p\utils\g2p.py", line 30, in phonemizer_ja = EspeakBackend( File "F:\maskgct\maskgct\venv\lib\site-packages\phonemizer\backend\espeak\espeak.py", line 49, in **init** self._espeak.set_voice(language) File "F:\maskgct\maskgct\venv\lib\site-packages\phonemizer\backend\espeak\wrapper.py", line 249, in set_voice raise RuntimeError( # pragma: nocover RuntimeError: failed to load voice "ja"
> > (venv) F:\maskgct\maskgct>
> 
> fixed~ try running `pip install -r requirements.txt` again

could you tell me what changes ？
